image: node:14.16.0

stages:
  - release
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/

release-patch:
  stage: release
  when: manual
  only:
    - master
  after_script:
    - git push repo HEAD:master --tags
  script:
    - npm version patch -m "Release %s"
  before_script:
    - git config --global user.email "bang@eoh.io"
    - git config --global user.name "Bang Dao"
    - git remote add repo https://react-native-smart-parking:$PROJECT_ACCESS_TOKEN@gitlab.com/eohio/react-native-smart-parking.git


release-minor:
  stage: release
  when: manual
  extends: release-patch
  script:
    - npm version minor -m "Release %s"


release-major:
  stage: release
  when: manual
  extends: release-patch
  script:
    - npm version major -m "Release %s"


publish-npm:
  stage: publish
  only:
    - /\d+\.\d+\.\d+/
  script:
    - git fetch origin master
    - apt list openssh-client -a
    - eval $(ssh-agent -s)
    - chmod 600 $GITHUB_DEPLOY_KEY
    - ssh-add $GITHUB_DEPLOY_KEY
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
    - git remote add github git@github.com:eohjsc/react-native-smart-parking.git
    - ssh -o StrictHostKeyChecking=no git@github.com || echo "Good"
    - git push -f github origin/master:master
    - npm publish
