image: node:14.16.0

stages:
  - check
  - test
  - release
  - publish

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - vendor/


check-basic-rule:
  stage: check
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-check/
      - $CI_COMMIT_MESSAGE =~ /Release \d+\.\d+\.\d+/
      - $CI_COMMIT_REF_SLUG =~ /bumpversion/
      - $CI_COMMIT_REF_SLUG =~ /chore/
      - $E2E_PATH
    refs:
      - master
  script:
    - git fetch origin master
    - yarn run check_translation_file_change
    - yarn run check_create_within_act

test_mr:
  stage: test
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-test/
      - $CI_COMMIT_MESSAGE =~ /Release \d+\.\d+\.\d+/
      - $E2E_PATH
  script:
    - if [ -e package-lock.json ]; then echo 'Please use yarn for package management.' && exit 1; else echo 'ok'; fi
    - yarn
    - yarn run lint
    - yarn run jest
  coverage: /^All files\s+\|\s+([0-9]*[.]?[0-9]{1,2})\s+\|\s+[0-9]*[.]?[0-9]{1,2}\s+\|\s+[0-9]*[.]?[0-9]{1,2}\s+\|\s+[0-9]*[.]?[0-9]{1,2}\s+\|/

release-patch:
  stage: release
  when: manual
  only:
    - master
  after_script:
    - git push repo HEAD:master --tags
  script:
    - npm version patch -m "Release %s"
  before_script:
    - git config --global user.email "bang@eoh.io"
    - git config --global user.name "Bang Dao"
    - git remote add repo https://react-native-smart-parking:$PROJECT_ACCESS_TOKEN@gitlab.com/eohio/react-native-smart-parking.git || echo "Done"


release-minor:
  stage: release
  when: manual
  extends: release-patch
  script:
    - npm version minor -m "Release %s"


release-major:
  stage: release
  when: manual
  extends: release-patch
  script:
    - npm version major -m "Release %s"


publish-npm:
  stage: publish
  only:
    - /\d+\.\d+\.\d+/
  script:
    - git fetch origin master
    - apt list openssh-client -a
    - eval $(ssh-agent -s)
    - chmod 600 $GITHUB_DEPLOY_KEY
    - ssh-add $GITHUB_DEPLOY_KEY
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
    - git remote add github git@github.com:eohjsc/react-native-smart-parking.git || echo "Good"
    - ssh -o StrictHostKeyChecking=no git@github.com || echo "Good"
    - git push -f github origin/master:master
    - npm publish
