const AsyncKeys = {
  PHONE_VERIFYING: 'PHONE_VERIFYING',
  VERIFY_OTP_AT: 'VERIFY_OTP_AT',
  RECENT_SEARCH: 'RECENT_SEARCH',
  IS_CONFIRM_TERM_SMART_PARKING: 'CHECK_TERM_SMART_PARKING',
};

export default AsyncKeys;
